# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: The Dump
email: liamniehusstaab@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
    Just a blog of random thoughts. Don't expect too much.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  niehusst
linkedin_username: liam-niehus-staab

markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"

# Build settings
# remote_theme: StartBootstrap/startbootstrap-clean-blog-jekyll
theme: jekyll-theme-clean-blog
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

